---
- hosts: all
  vars:
  #  local_app_dir: "/home/ludovico99/Scrivania/SEAt/SEAT_Project"
    local_home: "{{ lookup('env','HOME') }}"
    remote_home: "/home/ubuntu"
  #   remote_app_dir: "{{remote_home}}/SEAT_Project"
    local_aws_cred: "{{local_home}}/.aws"
    remote_aws_cred: "{{remote_home}}/"


 tasks:
# - name: copy application directory
#   copy:
#     src: "{{ local_app_dir }}/"
#     dest: "{{ remote_app_dir }}"
#   register: app  # save task output


  - name: copy aws credentials
    copy:
      src: "{{ local_aws_cred }}"
      dest: "{{ remote_aws_cred }}"

    - name: install python 3
      become: yes # we need root privileges 
      apt:
        name: python3
        state: present

    - name: Install docker packages
      become: yes # we need root privileges 
      remote_user: ubuntu
      apt:
        name: ['apt-transport-https','ca-certificates', 'curl', 'software-properties-common']
        state: present
        update_cache: yes
      tags:
        - docker

    - name: Add Docker s GPG key for ubuntu from official site
      become: yes # we need root privileges 
      remote_user: ubuntu
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
      tags:
        - docker

    - name: Verify gpg key with the fingerprint
      become: yes # we need root privileges 
      remote_user: ubuntu
      apt_key:
        id: 0EBFCD88
        state: present
      tags:
        - docker

    - name: Configure Docker for ubuntu stable repository
      become: yes # we need root privileges 
      remote_user: ubuntu
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
        state: present
        update_cache: yes
      tags:
        - docker

    - name: Install docker-ce
      become: yes # we need root privileges 
      remote_user: ubuntu
      apt:
        name: docker-ce
        state: present
        update_cache: yes
      tags:
        - docker

    - name: Add "ubuntu" user to "docker" group
      become: yes # we need root privileges 
      remote_user: ubuntu
      user:
        name: "ubuntu"
        group: "docker"
        append: yes
      tags:
        - docker

    - name: Install docker-compose from official github repo
      become: yes # we need root privileges 
      remote_user: ubuntu
      get_url:
        url : https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: 'u+x,g+x'

    - name: copy systemd unit file
      become: yes 
      copy:
        src: "progetto.service"
        dest: "/etc/systemd/system/"

    - name: enable and start systemd service
      become: yes 
      systemd:
        daemon_reload: yes
        state: restarted
        name: "progetto.service"
        enabled: yes
      #when: app.changed # only restart if new version was uploaded

  handlers:
    - name: restart docker
      service: 
        name: docker 
        state: restarted

   







