version: "3.9"
services:

  rabbitmq:
    container_name: rabbitmq
    image: 'rabbitmq:3.6-management-alpine'
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
        - /etc/rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf

    ports:
    - "5672:5672"
    - "15672:15672"

    
  front-end:
    build: 
      context: ./apiGateway
    ports:
      - "80:5000"
    environment:
      SCALE_FACTOR: $SCALE_FACTOR
      FLASK_ENV: development
    depends_on:
      - accounting
      - payment
      - service_registry
    
  
  accounting:
    build: ./accountingService
    volumes:
     - ./accountingService/src:/home/accountingService
    #   - ~/.aws/credentials:$HOME/.aws/credentials:ro
     - /home/ludovico99/.aws/:$HOME/.aws/
    environment:
      AMQP_URL: 'amqp://guest:guest@rabbitmq:5672?connection_attempts=5&retry_delay=15'
    ports:
      - "50052:50052"
    depends_on:
      - rabbitmq
      - service_registry

  email:
    build: ./emailService
    environment:
      AMQP_URL: 'amqp://rabbitmq:5672?connection_attempts=5&retry_delay=15'
    volumes:
     - ./emailService/src:/home/emailService
    depends_on:
      - accounting
      - rabbitmq

  service_registry:
    build: ./serviceRegistry
    ports:
      - "50000:50000"
    volumes:
      - ./serviceRegistry/src:/home/serviceRegistry
      - /home/ludovico99/.aws/:$HOME/.aws/
  
   
  payment: 
    build: ./paymentService
    environment:
      AMQP_URL: 'amqp://rabbitmq:5672?connection_attempts=5&retry_delay=5'
    volumes:
      - ./paymentService/src:/home/paymentService
      - /home/ludovico99/.aws/:$HOME/.aws/
    ports:
      - "50055-50075:50055"
    depends_on:
      - accounting
      - rabbitmq
      - service_registry

  quote: 
    build: ./quoteService
    volumes:
      - ./quoteService/src:/home/quoteService
      - /home/ludovico99/.aws/:$HOME/.aws/
    ports:
      - "50053:50053"
    depends_on:
      - accounting
      - service_registry


  reservation: 
    build: ./reservationService
    environment:
      AMQP_URL: 'amqp://rabbitmq?connection_attempts=5&retry_delay=5'
    volumes:
      - ./reservationService/src:/home/reservationService
      - /home/ludovico99/.aws/:$HOME/.aws/
    ports:
      - "50051:50051"
    depends_on:
      - accounting
      - rabbitmq
      - service_registry

  review: 
    build: ./reviewService
    volumes:
      - ./reviewService/src:/home/reviewService
      - /home/ludovico99/.aws/:$HOME/.aws/
    ports:
      - "50054:50054"
    depends_on:
      - accounting
      - service_registry

          