version: "3.9"
services:

  rabbitmq:
    container_name: rabbitmq
    image: 'rabbitmq:3.6-management-alpine'
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
        - /etc/rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    # environment:
    #   RABBITMQ_DEFAULT_USER: "guest"
    #   RABBITMQ_DEFAULT_PASS: "guest"
    ports:
    - "5672:5672"
    - "15672:15672"

    
  front-end:
    build: ./apiGateway
    ports:
      - "80:5000"
    environment:
      FLASK_ENV: development
    depends_on:
      - accounting
    

    # networks:
    #   static-network:
    #     ipv4_address: 172.24.0.2
  
  accounting:
    build: ./accountingService
    volumes:
     - ./accountingService/src:/home/accountingService
    #   - ~/.aws/credentials:$HOME/.aws/credentials:ro
    #   - ~/.aws/config:$HOME/.aws/config:ro
    environment:
      AMQP_URL: 'amqp://guest:guest@rabbitmq:5672?connection_attempts=5&retry_delay=15'
    ports:
      - "50052:50052"
    depends_on:
      - rabbitmq

  email:
    build: ./emailService
    environment:
      AMQP_URL: 'amqp://rabbitmq:5672?connection_attempts=5&retry_delay=15'
    volumes:
     - ./emailService/src:/home/emailService
    depends_on:
      - accounting
      - rabbitmq
   



  # payment: 
  #   build: ./paymentService
  #   environment:
  #     AMQP_URL: 'amqp://rabbitmq?connection_attempts=5&retry_delay=5'
  #   volumes:
  #     - ./paymentService/src:/home/paymentService
  #   ports:
  #     - "50055:50055"
  #   depends_on:
  #     - accounting
  #     - rabbitmq

  # quote: 
  #   build: ./quoteService
  #   volumes:
  #     - ./quoteService/src:/home/quoteService
  #   ports:
  #     - "50053:50053"
  #   depends_on:
  #     - accounting


  # reservation: 
  #   build: ./reservationService
  #   environment:
  #     AMQP_URL: 'amqp://rabbitmq?connection_attempts=5&retry_delay=5'
  #   volumes:
  #     - ./reservationService/src:/home/reservationService
  #   ports:
  #     - "50051:50051"
  #   depends_on:
  #     - accounting
  #     - rabbitmq

  # review: 
  #   build: ./reviewService
  #   volumes:
  #     - ./reviewService/src:/home/reviewService
  #   ports:
  #     - "50054:50054"
  #   depends_on:
  #     - accounting

    # networks:
    #   static-network:
    #     ipv4_address: 172.24.0.3

# networks:
#   static-network:
#     ipam:
#       config:
#         - subnet: 172.24.0.0/16
            #docker-compose v3+ do not use ip_range
          