version: "3.9"
services:

  rabbitmq:
    image: rabbitmq:3-management
    ports:
    - "5672:5672"
    - "15672:15672"
    
  front-end:
    build: ./apiGateway
    ports:
      - "80:5000"
    environment:
      FLASK_ENV: development
    depends_on:
      - accounting

    # networks:
    #   static-network:
    #     ipv4_address: 172.24.0.2
  
  accounting:
    build: ./accountingService
    volumes:
      - ~/.aws/:/home/.aws:ro
    ports:
      - "50052:50052"
    depends_on:
      - rabbitmq

  # email:
  #   build: ./emailService
  #   depends_on:
  #     - accounting

  # payment: 
  #   build: ./paymentService
  #   volumes:
  #     - .:/paymentService
  #   ports:
  #     - "50055:50055"
  #   depends_on:
  #     - accounting

    # networks:
    #   static-network:
    #     ipv4_address: 172.24.0.3

# networks:
#   static-network:
#     ipam:
#       config:
#         - subnet: 172.24.0.0/16
            #docker-compose v3+ do not use ip_range
          