# syntax=docker/dockerfile:1
FROM python:3.7-alpine
WORKDIR /home
ENV FLASK_DEBUG=app.py
COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt
COPY src apiGateway
ENV PYTHONUNBUFFERED=1
CMD ["python","apiGateway/app.py"]