# syntax=docker/dockerfile:1
FROM python:3.7-alpine
WORKDIR /home
#RUN apk add --no-cache gcc musl-dev linux-headers
COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt
ENV PYTHONUNBUFFERED=1
CMD ["python", "paymentService/main.py"]