# syntax=docker/dockerfile:1
FROM python:3.7-alpine
WORKDIR /Seat
#RUN apk add --no-cache gcc musl-dev linux-headers
COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt
EXPOSE 50055
COPY . .
CMD ["python", "paymentService/src/main.py"]