# syntax=docker/dockerfile:1
FROM python:3.7-alpine
WORKDIR /accountingService
#RUN apk add --no-cache gcc musl-dev linux-headers
COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt
EXPOSE 50052
COPY . .
CMD ["python", "accountingService/src/main.py"]