# syntax=docker/dockerfile:1
FROM python:3.7-alpine
WORKDIR /home
RUN apk add --no-cache gcc musl-dev linux-headers
RUN pip install --upgrade pip
RUN apk add --no-cache aws-cli
COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt
EXPOSE 50051
#COPY src accountingService
COPY credentials /root/.aws/
ENV PYTHONUNBUFFERED=1
# WORKDIR /accountingService
CMD ["python", "reservationService/main.py"]