# syntax=docker/dockerfile:1
FROM python:3.7-alpine
WORKDIR /home
#RUN apk add --no-cache gcc musl-dev linux-headers
RUN apk add --no-cache aws-cli
COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt
EXPOSE 50053
#COPY src accountingService
COPY credentials /root/.aws/
# WORKDIR /accountingService
CMD ["python", "quoteService/main.py"]